POST http://localhost:3000/api/historias
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="titulo"

Rosario Central
--boundary123
Content-Disposition: form-data; name="fechaDesde"

2025-08-08
--boundary123
Content-Disposition: form-data; name="fechaHasta"

2025-08-15
--boundary123
Content-Disposition: form-data; name="descripcion"

Central el mas grande
--boundary123
Content-Disposition: form-data; name="puntoDeInteres"

8
--boundary123
Content-Disposition: form-data; name="imagen"; filename="foto.jpg"
Content-Type: image/jpeg

< ./foto.jpg
--boundary123--