### Find All
GET http://localhost:3000/api/puntosDeInteres

### Find One
GET http://localhost:3000/api/puntosDeInteres/4

### Add
POST http://localhost:3000/api/puntosDeInteres
Content-Type: application/json

{
  "nombre" : "Catedral",
  "descripcion" : "Barrio Historico",
  "imagen" : "foto.png",
  "calle" : "Avellaneda",
  "altura" : 0,
  "privado" : false,
  "tags" : [],
  "eventos" : [],
  "localidad" : 1,
  "valoraciones" : [],
  "usuario" : 1, 
  "historias" : []
}
### Add
POST http://localhost:3000/api/puntosDeInteres
Content-Type: application/json

{
  "nombre" : "Showcase",
  "descripcion" : "CineMax Showcase",
  "imagen" : "",
  "calle" : "Junín",
  "altura" : 5010,
  "privado" : true,
  "tags" : [],
  "eventos" : [],
  "localidad" : 4,
  "valoraciones" : [],
  "usuario" : 2,
  "historias" : []
}

### Delete
DELETE http://localhost:3000/api/puntosDeInteres/3

### Update
PUT http://localhost:3000/api/puntosDeInteres/4
Content-Type: application/json

{
  "nombre" : "Alto Rosario 2",
  "descripcion" : "Shopping Alto Rosario Editado",
  "imagen" : "shopping.png",
  "calle" : "Junín",
  "altura" : 5001,
  "privado" : true,
  "tags" : [4,6],
  "eventos" : []
}