### obtener todos los tags 
GET http://localhost:3000/api/tags


### obtener un tag por id
GET http://localhost:3000/api/tags/1


### crear un nuevo tag
POST http://localhost:3000/api/tags
Content-Type: application/json

{
  "nombre" : "Literatura",
  "descripcion" : "Lugar donde se puede leer libros",
  "tipo" : "Entretenimiento"
}


### modificar un tag (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/tags/1
Content-Type: application/json

{
  "nombre" : "Deportes Acuaticos",
  "descripcion" : "Actividad deportiva que incluye natacion",
  "tipo" : "Ejercitación"
}


### modificar un tag (PUT - recurso parcial)
PATCH http://localhost:3000/api/tags/4
Content-Type: application/json

{
  "nombre" : "Gimnasio",
  "descipcion" : "Entrenamientos de fuerza"
}


### borrar un tag
DELETE http://localhost:3000/api/tags/1