###GET ALL
DELETE  http://localhost:3000/api/usuarios/27


###POST
POST http://localhost:3000/api/usuarios/register
Content-Type: application/json

{
  "nombre": "Juan Perez",
  "password": "1234",
  "gmail": "juanperez@gmail.com",
  "tipo": "admin",
  "cuit": "20123456789",
  "password": "clave123",
  "localidad": 7,
  "puntosDeInteres" : [],
  "agendaPDI" : [],
  "valoraciones": [],
  "favoritos": []
}


###POST
POST http://localhost:3000/api/usuarios/register
Content-Type: application/json

{
  "nombre": "administrador",
  "gmail": "administrador@gmail.com",
  "tipo": "admin",
  "cuit": "20123451239",
  "password": "123456",
  "localidad": 2,
  "puntosDeInteres" : [],
  "agendaPDI" : [],
  "valoraciones": [],
  "favoritos": []
}


###POST
POST http://localhost:3000/api/usuarios/register
Content-Type: application/json

{
  "nombre": "Satur3",
  "gmail": "satur3@gmail.com",
  "tipo": "creador",
  "password": "123456"
}


###POST
PUT http://localhost:3000/api/usuarios/31
Content-Type: application/json

{
  "nombre": "Satur2 Modificado",
  "password": "nuevaclave123"
}

### register
POST http://localhost:3000/api/usuarios/register
Content-Type: application/json

{
    "nombre": "Administrador",
    "tipo": "admin",
    "cuit": "20123456789",
    "gmail": "administrador@gmail.com",
    "password": "123456",
    "localidad": 1
}

### login
POST http://localhost:3000/api/usuarios/login
Content-Type: application/json

{
    "gmail": "satur2@gmail.com",
    "password": "nuevaclave123"
}
