###GET ALL
GET http://localhost:3000/api/usuarios


###POST
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
  "nombre": "Juan Perez",
  "password": "1234",
  "gmail": "juanperez@gmail",
  "tipo": "cliente",
  "cuit": "20-12345678-9",
  "password": "clave",
  "localidad": 7,
  "puntosDeInteres" : [],
  "agendaPDI" : [],
  "valoraciones": [],
  "favoritos": []
}


###POST
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
  "nombre": "Gabi gol",
  "gmail": "gabigol@gmail",
  "tipo": "creador",
  "cuit": "20-12345123-9",
  "localidad": 2,
  "puntosDeInteres" : [],
  "agendaPDI" : [],
  "valoraciones": [],
  "favoritos": []
}


###POST
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
  "nombre": "Colo Satur",
  "gmail": "saturColo@gmail",
  "tipo": "creador",
  "cuit": "20-199999-9",
  "localidad": 3,
  "puntosDeInteres" : [],
  "agendaPDI" : [],
  "valoraciones": [],
  "favoritos": []
}


###POST
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
  "nombre": "Fideo Di Maria",
  "gmail": "DimariaGol@gmail",
  "tipo": "cliente",
  "password": "123",
  "cuit": "20-4567823-9",
  "localidad": 2,
  "puntosDeInteres" : [],
  "agendaPDI" : [],
  "valoraciones": [],
  "favoritos": []
}

### login
POST http://localhost:3000/api/usuarios/register
Content-Type: application/json

{
    "nombre": "Administrador",
    "tipo": "admin",
    "cuit": "20-12345678-9",
    "gmail": "administrador@gmail.com",
    "password": "123",
    "localidad": 1
}