###GET
GET http://localhost:3000/api/localidades

###GET ONE
GET http://localhost:3000/api/localidades/1

###POST
POST http://localhost:3000/api/localidades
Content-Type: application/json

{
    "nombre": "Mar Del Plata",
    "codUta": "U123",
    "latitud": -27.4228,
    "longitud": -50.265,
    "provincia": 1
}
###POST
POST http://localhost:3000/api/localidades
Content-Type: application/json

{
    "nombre": "San Jeronimo",
    "latitud": -33.6333,
    "longitud": -60.6393,
    "provincia": 4
}

###PUT
POST  http://localhost:3000/api/localidades
Content-Type: application/json

{
    "nombre": "Roldan",
    "codUta": "UTA123",
    "latitud": -31.6333,
    "longitud": -60.7003,
    "provincia": 4
}
###PUT
POST  http://localhost:3000/api/localidades
Content-Type: application/json

{
    "nombre": "CABA",
    "codUta": "CABA",
    "latitud": -34.6037,
    "longitud": -58.3816,
    "provincia": 1
}

###DELETE
DELETE http://localhost:3000/api/localidades/1
