###GET
GET http://localhost:3000/api/localidades

###GET ONE
POST http://localhost:3000/api/localidades/filtro
Content-Type: application/json

{
    "provincia": 4,
    "busqueda": "San"
}

###POST
POST http://localhost:3000/api/localidades
Content-Type: application/json

{
    "nombre": "Test",
    "latitud": -27.4228,
    "longitud": -50.265,
    "provincia": 1,
    "imagen": "bee0891c-2873-434e-803e-81b5e8803416.jpg"
}
###POST
POST http://localhost:3000/api/localidades
Content-Type: application/json

{
    "nombre": "San Jeronimo",
    "latitud": -33.6333,
    "longitud": -60.6393,
    "provincia": 4
}

###PUT
PUT  http://localhost:3000/api/localidades/15
Content-Type: application/json

{
    "imagen": "1a1e419c-a4ad-4020-b025-ba9a7d525b1c.jpg"
}
###PUT
PUT  http://localhost:3000/api/localidades
Content-Type: application/json

{
    "nombre": "CABA",
    "codUta": "CABA",
    "latitud": -34.6037,
    "longitud": -58.3816,
    "provincia": 1
}

###DELETE
DELETE http://localhost:3000/api/localidades/15
